# Главный выключатель
scriptEnabled=false

# Обработка объявлений
autoCatch=true
autoAd=true
suggestions=true
skipShort=false
skipUnknown=false
quickButtons=true
wideDialog=true
# 1 автоматический, 2 ручной
editMode=1
# 1 LS, 2 LV, 3 SF
newsEdition=1

# Элементы на экране
wikiEnabled=true
adWidget=true
hideAccOnZoom=true
historyPanel=true
photoMarker=true

# Тайминги и вид
delay=10
simThreshold=60
notifyTime=2500
opacity=0.90
# 1 синяя, 2 зелёная, 3 фиолетовая, 4 красная, 5 розовая, 6 серая
theme=6
# 1 выкл, 2 снег, 3 пыль, 4 дождь, 5 сердечки, 6 цветочки
particles=3

# Клавиши. Код клавиши, назначается в окне скрипта
panelHotkey=106
listHotkey=0
adHotkey=97
buyHotkey=0
sellHotkey=0

# Положение виджета объявлений на экране
adTimerX=-1.0000
adTimerY=-1.0000
